site_name: OpenCan
nav:
  - 'Start':
    - 'Introduction': 'index.md'
  - 'Learn':
    - 'Overview': 'learn.md'
    - 'Creating a new IC app': 'getting-started.md'
  - 'Tools':
    - 'fungible-tokens.md'
    - 'non-fungible-tokens.md'
theme:
    name: 'mkdocs'
    custom_dir: 'custom_theme/'